/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/widgets/Accordion.vue')['default']
    BlockDashboard: typeof import('./components/widgets/BlockDashboard.vue')['default']
    Card: typeof import('./components/base/Card.vue')['default']
    DiskSpace: typeof import('./components/widgets/DiskSpace.vue')['default']
    FastContact: typeof import('./components/widgets/FastContact.vue')['default']
    GaugeChart: typeof import('./components/widgets/GaugeChart.vue')['default']
    Inbox: typeof import('./components/widgets/Inbox.vue')['default']
    LastDaysStats: typeof import('./components/widgets/LastDaysStats.vue')['default']
    LastMonthRevenue: typeof import('./components/widgets/LastMonthRevenue.vue')['default']
    LastRegisteredUser: typeof import('./components/widgets/LastRegisteredUser.vue')['default']
    LatestNews: typeof import('./components/widgets/LatestNews.vue')['default']
    Modal: typeof import('./components/widgets/Modal.vue')['default']
    RedditFeed: typeof import('./components/widgets/RedditFeed.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerUptime: typeof import('./components/widgets/ServerUptime.vue')['default']
    SiteBandwidth: typeof import('./components/widgets/SiteBandwidth.vue')['default']
    TotalSubscribers: typeof import('./components/widgets/TotalSubscribers.vue')['default']
    TwitterFeed: typeof import('./components/widgets/TwitterFeed.vue')['default']
    UserProfile: typeof import('./components/widgets/UserProfile.vue')['default']
    Widget: typeof import('./components/base/Widget.vue')['default']
  }
}
